spring:
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        initialization-mode: always
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: admin

endpoints:
    book-endpoint: http://localhost:10011/api/books
    user-endpoint: http://localhost:10010/api/users
    
server:
    port: 10012