spring:
    application:
        name: library-service
    jpa:
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        initialization-mode: always
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: admin

endpoints:
    book-endpoint: http://book-service/api/books
    user-endpoint: http://user-service/api/users
    
server:
    port: 10012
    
eureka:
  client:
    service-url: 
        defaultZone: http://localhost:10010/eureka

management:
    endpoints:
        web:
            expose: hystrix.stream
            exposure:
                include: hystrix.stream

hystrix.dashboard.proxyStreamAllowList: "*"